// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protos/proxima.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.proxima;

@kotlin.jvm.JvmName("-initializeping")
public inline fun ping(block: com.example.proxima.PingKt.Dsl.() -> kotlin.Unit): com.example.proxima.Ping =
  com.example.proxima.PingKt.Dsl._create(com.example.proxima.Ping.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proxima.Ping`
 */
public object PingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.proxima.Ping.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.proxima.Ping.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.proxima.Ping = _builder.build()

    /**
     * `int32 uid = 1;`
     */
    public var uid: kotlin.Int
      @JvmName("getUid")
      get() = _builder.getUid()
      @JvmName("setUid")
      set(value) {
        _builder.setUid(value)
      }
    /**
     * `int32 uid = 1;`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * `.proxima.User owner = 2;`
     */
    public var owner: com.example.proxima.User
      @JvmName("getOwner")
      get() = _builder.getOwner()
      @JvmName("setOwner")
      set(value) {
        _builder.setOwner(value)
      }
    /**
     * `.proxima.User owner = 2;`
     */
    public fun clearOwner() {
      _builder.clearOwner()
    }
    /**
     * `.proxima.User owner = 2;`
     * @return Whether the owner field is set.
     */
    public fun hasOwner(): kotlin.Boolean {
      return _builder.hasOwner()
    }

    /**
     * `.google.type.LatLng latlng = 3;`
     */
    public var latlng: com.google.type.LatLng
      @JvmName("getLatlng")
      get() = _builder.getLatlng()
      @JvmName("setLatlng")
      set(value) {
        _builder.setLatlng(value)
      }
    /**
     * `.google.type.LatLng latlng = 3;`
     */
    public fun clearLatlng() {
      _builder.clearLatlng()
    }
    /**
     * `.google.type.LatLng latlng = 3;`
     * @return Whether the latlng field is set.
     */
    public fun hasLatlng(): kotlin.Boolean {
      return _builder.hasLatlng()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tags = 4;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTagsList()
      )
    /**
     * `repeated string tags = 4;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * `repeated string tags = 4;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tags = 4;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * `repeated string tags = 4;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tags = 4;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * `repeated string tags = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }
    /**
     * `string description = 5;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * `string description = 5;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OrbitProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .proxima.User orbit = 6;`
     */
     public val orbit: com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOrbitList()
      )
    /**
     * `repeated .proxima.User orbit = 6;`
     * @param value The orbit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOrbit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.add(value: com.example.proxima.User) {
      _builder.addOrbit(value)
    }
    /**
     * `repeated .proxima.User orbit = 6;`
     * @param value The orbit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOrbit")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.plusAssign(value: com.example.proxima.User) {
      add(value)
    }
    /**
     * `repeated .proxima.User orbit = 6;`
     * @param values The orbit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOrbit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.addAll(values: kotlin.collections.Iterable<com.example.proxima.User>) {
      _builder.addAllOrbit(values)
    }
    /**
     * `repeated .proxima.User orbit = 6;`
     * @param values The orbit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOrbit")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.proxima.User>) {
      addAll(values)
    }
    /**
     * `repeated .proxima.User orbit = 6;`
     * @param index The index to set the value at.
     * @param value The orbit to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOrbit")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.set(index: kotlin.Int, value: com.example.proxima.User) {
      _builder.setOrbit(index, value)
    }
    /**
     * `repeated .proxima.User orbit = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOrbit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, OrbitProxy>.clear() {
      _builder.clearOrbit()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HitProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     */
     public val hit: com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getHitList()
      )
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     * @param value The hit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addHit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.add(value: com.example.proxima.User) {
      _builder.addHit(value)
    }
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     * @param value The hit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignHit")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.plusAssign(value: com.example.proxima.User) {
      add(value)
    }
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     * @param values The hit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllHit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.addAll(values: kotlin.collections.Iterable<com.example.proxima.User>) {
      _builder.addAllHit(values)
    }
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     * @param values The hit to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllHit")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.proxima.User>) {
      addAll(values)
    }
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     * @param index The index to set the value at.
     * @param value The hit to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setHit")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.set(index: kotlin.Int, value: com.example.proxima.User) {
      _builder.setHit(index, value)
    }
    /**
     * ```
     * users who have been hit by the ping
     * ```
     *
     * `repeated .proxima.User hit = 7;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearHit")
    public fun com.google.protobuf.kotlin.DslList<com.example.proxima.User, HitProxy>.clear() {
      _builder.clearHit()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.proxima.Ping.copy(block: `com.example.proxima`.PingKt.Dsl.() -> kotlin.Unit): com.example.proxima.Ping =
  `com.example.proxima`.PingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.proxima.PingOrBuilder.ownerOrNull: com.example.proxima.User?
  get() = if (hasOwner()) getOwner() else null

public val com.example.proxima.PingOrBuilder.latlngOrNull: com.google.type.LatLng?
  get() = if (hasLatlng()) getLatlng() else null

