// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

/**
 * Protobuf type {@code proxima.Ping}
 */
public final class Ping extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proxima.Ping)
    PingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ping.newBuilder() to construct.
  private Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ping() {
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    description_ = "";
    orbit_ = java.util.Collections.emptyList();
    hit_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ping();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.proxima.ProximaProto.internal_static_proxima_Ping_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.proxima.ProximaProto.internal_static_proxima_Ping_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.proxima.Ping.class, com.example.proxima.Ping.Builder.class);
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private int uid_ = 0;
  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public int getUid() {
    return uid_;
  }

  public static final int OWNER_FIELD_NUMBER = 2;
  private com.example.proxima.User owner_;
  /**
   * <code>.proxima.User owner = 2;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proxima.User owner = 2;</code>
   * @return The owner.
   */
  @java.lang.Override
  public com.example.proxima.User getOwner() {
    return owner_ == null ? com.example.proxima.User.getDefaultInstance() : owner_;
  }
  /**
   * <code>.proxima.User owner = 2;</code>
   */
  @java.lang.Override
  public com.example.proxima.UserOrBuilder getOwnerOrBuilder() {
    return owner_ == null ? com.example.proxima.User.getDefaultInstance() : owner_;
  }

  public static final int LATLNG_FIELD_NUMBER = 3;
  private com.google.type.LatLng latlng_;
  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   * @return Whether the latlng field is set.
   */
  @java.lang.Override
  public boolean hasLatlng() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   * @return The latlng.
   */
  @java.lang.Override
  public com.google.type.LatLng getLatlng() {
    return latlng_ == null ? com.google.type.LatLng.getDefaultInstance() : latlng_;
  }
  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   */
  @java.lang.Override
  public com.google.type.LatLngOrBuilder getLatlngOrBuilder() {
    return latlng_ == null ? com.google.type.LatLng.getDefaultInstance() : latlng_;
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string tags = 4;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORBIT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.example.proxima.User> orbit_;
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.proxima.User> getOrbitList() {
    return orbit_;
  }
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getOrbitOrBuilderList() {
    return orbit_;
  }
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  @java.lang.Override
  public int getOrbitCount() {
    return orbit_.size();
  }
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  @java.lang.Override
  public com.example.proxima.User getOrbit(int index) {
    return orbit_.get(index);
  }
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  @java.lang.Override
  public com.example.proxima.UserOrBuilder getOrbitOrBuilder(
      int index) {
    return orbit_.get(index);
  }

  public static final int HIT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.example.proxima.User> hit_;
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.proxima.User> getHitList() {
    return hit_;
  }
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getHitOrBuilderList() {
    return hit_;
  }
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  @java.lang.Override
  public int getHitCount() {
    return hit_.size();
  }
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  @java.lang.Override
  public com.example.proxima.User getHit(int index) {
    return hit_.get(index);
  }
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  @java.lang.Override
  public com.example.proxima.UserOrBuilder getHitOrBuilder(
      int index) {
    return hit_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0) {
      output.writeInt32(1, uid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getOwner());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getLatlng());
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tags_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    for (int i = 0; i < orbit_.size(); i++) {
      output.writeMessage(6, orbit_.get(i));
    }
    for (int i = 0; i < hit_.size(); i++) {
      output.writeMessage(7, hit_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, uid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOwner());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLatlng());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    for (int i = 0; i < orbit_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, orbit_.get(i));
    }
    for (int i = 0; i < hit_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, hit_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.proxima.Ping)) {
      return super.equals(obj);
    }
    com.example.proxima.Ping other = (com.example.proxima.Ping) obj;

    if (getUid()
        != other.getUid()) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (hasLatlng() != other.hasLatlng()) return false;
    if (hasLatlng()) {
      if (!getLatlng()
          .equals(other.getLatlng())) return false;
    }
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getOrbitList()
        .equals(other.getOrbitList())) return false;
    if (!getHitList()
        .equals(other.getHitList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    if (hasLatlng()) {
      hash = (37 * hash) + LATLNG_FIELD_NUMBER;
      hash = (53 * hash) + getLatlng().hashCode();
    }
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getOrbitCount() > 0) {
      hash = (37 * hash) + ORBIT_FIELD_NUMBER;
      hash = (53 * hash) + getOrbitList().hashCode();
    }
    if (getHitCount() > 0) {
      hash = (37 * hash) + HIT_FIELD_NUMBER;
      hash = (53 * hash) + getHitList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.proxima.Ping parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.Ping parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.Ping parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.Ping parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.Ping parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.Ping parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.Ping parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.proxima.Ping parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.proxima.Ping parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.proxima.Ping parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.proxima.Ping parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.proxima.Ping parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.proxima.Ping prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proxima.Ping}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proxima.Ping)
      com.example.proxima.PingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proxima.ProximaProto.internal_static_proxima_Ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proxima.ProximaProto.internal_static_proxima_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proxima.Ping.class, com.example.proxima.Ping.Builder.class);
    }

    // Construct using com.example.proxima.Ping.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOwnerFieldBuilder();
        getLatlngFieldBuilder();
        getOrbitFieldBuilder();
        getHitFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = 0;
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      latlng_ = null;
      if (latlngBuilder_ != null) {
        latlngBuilder_.dispose();
        latlngBuilder_ = null;
      }
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      description_ = "";
      if (orbitBuilder_ == null) {
        orbit_ = java.util.Collections.emptyList();
      } else {
        orbit_ = null;
        orbitBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (hitBuilder_ == null) {
        hit_ = java.util.Collections.emptyList();
      } else {
        hit_ = null;
        hitBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.proxima.ProximaProto.internal_static_proxima_Ping_descriptor;
    }

    @java.lang.Override
    public com.example.proxima.Ping getDefaultInstanceForType() {
      return com.example.proxima.Ping.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.proxima.Ping build() {
      com.example.proxima.Ping result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.proxima.Ping buildPartial() {
      com.example.proxima.Ping result = new com.example.proxima.Ping(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.proxima.Ping result) {
      if (orbitBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          orbit_ = java.util.Collections.unmodifiableList(orbit_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.orbit_ = orbit_;
      } else {
        result.orbit_ = orbitBuilder_.build();
      }
      if (hitBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          hit_ = java.util.Collections.unmodifiableList(hit_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.hit_ = hit_;
      } else {
        result.hit_ = hitBuilder_.build();
      }
    }

    private void buildPartial0(com.example.proxima.Ping result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.owner_ = ownerBuilder_ == null
            ? owner_
            : ownerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.latlng_ = latlngBuilder_ == null
            ? latlng_
            : latlngBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.description_ = description_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.proxima.Ping) {
        return mergeFrom((com.example.proxima.Ping)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.proxima.Ping other) {
      if (other == com.example.proxima.Ping.getDefaultInstance()) return this;
      if (other.getUid() != 0) {
        setUid(other.getUid());
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (other.hasLatlng()) {
        mergeLatlng(other.getLatlng());
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000008;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (orbitBuilder_ == null) {
        if (!other.orbit_.isEmpty()) {
          if (orbit_.isEmpty()) {
            orbit_ = other.orbit_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureOrbitIsMutable();
            orbit_.addAll(other.orbit_);
          }
          onChanged();
        }
      } else {
        if (!other.orbit_.isEmpty()) {
          if (orbitBuilder_.isEmpty()) {
            orbitBuilder_.dispose();
            orbitBuilder_ = null;
            orbit_ = other.orbit_;
            bitField0_ = (bitField0_ & ~0x00000020);
            orbitBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrbitFieldBuilder() : null;
          } else {
            orbitBuilder_.addAllMessages(other.orbit_);
          }
        }
      }
      if (hitBuilder_ == null) {
        if (!other.hit_.isEmpty()) {
          if (hit_.isEmpty()) {
            hit_ = other.hit_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureHitIsMutable();
            hit_.addAll(other.hit_);
          }
          onChanged();
        }
      } else {
        if (!other.hit_.isEmpty()) {
          if (hitBuilder_.isEmpty()) {
            hitBuilder_.dispose();
            hitBuilder_ = null;
            hit_ = other.hit_;
            bitField0_ = (bitField0_ & ~0x00000040);
            hitBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHitFieldBuilder() : null;
          } else {
            hitBuilder_.addAllMessages(other.hit_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              uid_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getOwnerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getLatlngFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 34
            case 42: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.example.proxima.User m =
                  input.readMessage(
                      com.example.proxima.User.parser(),
                      extensionRegistry);
              if (orbitBuilder_ == null) {
                ensureOrbitIsMutable();
                orbit_.add(m);
              } else {
                orbitBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              com.example.proxima.User m =
                  input.readMessage(
                      com.example.proxima.User.parser(),
                      extensionRegistry);
              if (hitBuilder_ == null) {
                ensureHitIsMutable();
                hit_.add(m);
              } else {
                hitBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int uid_ ;
    /**
     * <code>int32 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(int value) {

      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = 0;
      onChanged();
      return this;
    }

    private com.example.proxima.User owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> ownerBuilder_;
    /**
     * <code>.proxima.User owner = 2;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     * @return The owner.
     */
    public com.example.proxima.User getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? com.example.proxima.User.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public Builder setOwner(com.example.proxima.User value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
      } else {
        ownerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public Builder setOwner(
        com.example.proxima.User.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public Builder mergeOwner(com.example.proxima.User value) {
      if (ownerBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          owner_ != null &&
          owner_ != com.example.proxima.User.getDefaultInstance()) {
          getOwnerBuilder().mergeFrom(value);
        } else {
          owner_ = value;
        }
      } else {
        ownerBuilder_.mergeFrom(value);
      }
      if (owner_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public Builder clearOwner() {
      bitField0_ = (bitField0_ & ~0x00000002);
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public com.example.proxima.User.Builder getOwnerBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    public com.example.proxima.UserOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            com.example.proxima.User.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.proxima.User owner = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private com.google.type.LatLng latlng_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> latlngBuilder_;
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     * @return Whether the latlng field is set.
     */
    public boolean hasLatlng() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     * @return The latlng.
     */
    public com.google.type.LatLng getLatlng() {
      if (latlngBuilder_ == null) {
        return latlng_ == null ? com.google.type.LatLng.getDefaultInstance() : latlng_;
      } else {
        return latlngBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public Builder setLatlng(com.google.type.LatLng value) {
      if (latlngBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        latlng_ = value;
      } else {
        latlngBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public Builder setLatlng(
        com.google.type.LatLng.Builder builderForValue) {
      if (latlngBuilder_ == null) {
        latlng_ = builderForValue.build();
      } else {
        latlngBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public Builder mergeLatlng(com.google.type.LatLng value) {
      if (latlngBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          latlng_ != null &&
          latlng_ != com.google.type.LatLng.getDefaultInstance()) {
          getLatlngBuilder().mergeFrom(value);
        } else {
          latlng_ = value;
        }
      } else {
        latlngBuilder_.mergeFrom(value);
      }
      if (latlng_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public Builder clearLatlng() {
      bitField0_ = (bitField0_ & ~0x00000004);
      latlng_ = null;
      if (latlngBuilder_ != null) {
        latlngBuilder_.dispose();
        latlngBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public com.google.type.LatLng.Builder getLatlngBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getLatlngFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    public com.google.type.LatLngOrBuilder getLatlngOrBuilder() {
      if (latlngBuilder_ != null) {
        return latlngBuilder_.getMessageOrBuilder();
      } else {
        return latlng_ == null ?
            com.google.type.LatLng.getDefaultInstance() : latlng_;
      }
    }
    /**
     * <code>.google.type.LatLng latlng = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> 
        getLatlngFieldBuilder() {
      if (latlngBuilder_ == null) {
        latlngBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder>(
                getLatlng(),
                getParentForChildren(),
                isClean());
        latlng_ = null;
      }
      return latlngBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.util.List<com.example.proxima.User> orbit_ =
      java.util.Collections.emptyList();
    private void ensureOrbitIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        orbit_ = new java.util.ArrayList<com.example.proxima.User>(orbit_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> orbitBuilder_;

    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public java.util.List<com.example.proxima.User> getOrbitList() {
      if (orbitBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orbit_);
      } else {
        return orbitBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public int getOrbitCount() {
      if (orbitBuilder_ == null) {
        return orbit_.size();
      } else {
        return orbitBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public com.example.proxima.User getOrbit(int index) {
      if (orbitBuilder_ == null) {
        return orbit_.get(index);
      } else {
        return orbitBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder setOrbit(
        int index, com.example.proxima.User value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.set(index, value);
        onChanged();
      } else {
        orbitBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder setOrbit(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.set(index, builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder addOrbit(com.example.proxima.User value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.add(value);
        onChanged();
      } else {
        orbitBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder addOrbit(
        int index, com.example.proxima.User value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.add(index, value);
        onChanged();
      } else {
        orbitBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder addOrbit(
        com.example.proxima.User.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.add(builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder addOrbit(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.add(index, builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder addAllOrbit(
        java.lang.Iterable<? extends com.example.proxima.User> values) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orbit_);
        onChanged();
      } else {
        orbitBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder clearOrbit() {
      if (orbitBuilder_ == null) {
        orbit_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        orbitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public Builder removeOrbit(int index) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.remove(index);
        onChanged();
      } else {
        orbitBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public com.example.proxima.User.Builder getOrbitBuilder(
        int index) {
      return getOrbitFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public com.example.proxima.UserOrBuilder getOrbitOrBuilder(
        int index) {
      if (orbitBuilder_ == null) {
        return orbit_.get(index);  } else {
        return orbitBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public java.util.List<? extends com.example.proxima.UserOrBuilder> 
         getOrbitOrBuilderList() {
      if (orbitBuilder_ != null) {
        return orbitBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orbit_);
      }
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public com.example.proxima.User.Builder addOrbitBuilder() {
      return getOrbitFieldBuilder().addBuilder(
          com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public com.example.proxima.User.Builder addOrbitBuilder(
        int index) {
      return getOrbitFieldBuilder().addBuilder(
          index, com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User orbit = 6;</code>
     */
    public java.util.List<com.example.proxima.User.Builder> 
         getOrbitBuilderList() {
      return getOrbitFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> 
        getOrbitFieldBuilder() {
      if (orbitBuilder_ == null) {
        orbitBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder>(
                orbit_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        orbit_ = null;
      }
      return orbitBuilder_;
    }

    private java.util.List<com.example.proxima.User> hit_ =
      java.util.Collections.emptyList();
    private void ensureHitIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        hit_ = new java.util.ArrayList<com.example.proxima.User>(hit_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> hitBuilder_;

    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public java.util.List<com.example.proxima.User> getHitList() {
      if (hitBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hit_);
      } else {
        return hitBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public int getHitCount() {
      if (hitBuilder_ == null) {
        return hit_.size();
      } else {
        return hitBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public com.example.proxima.User getHit(int index) {
      if (hitBuilder_ == null) {
        return hit_.get(index);
      } else {
        return hitBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder setHit(
        int index, com.example.proxima.User value) {
      if (hitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitIsMutable();
        hit_.set(index, value);
        onChanged();
      } else {
        hitBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder setHit(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (hitBuilder_ == null) {
        ensureHitIsMutable();
        hit_.set(index, builderForValue.build());
        onChanged();
      } else {
        hitBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder addHit(com.example.proxima.User value) {
      if (hitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitIsMutable();
        hit_.add(value);
        onChanged();
      } else {
        hitBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder addHit(
        int index, com.example.proxima.User value) {
      if (hitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitIsMutable();
        hit_.add(index, value);
        onChanged();
      } else {
        hitBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder addHit(
        com.example.proxima.User.Builder builderForValue) {
      if (hitBuilder_ == null) {
        ensureHitIsMutable();
        hit_.add(builderForValue.build());
        onChanged();
      } else {
        hitBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder addHit(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (hitBuilder_ == null) {
        ensureHitIsMutable();
        hit_.add(index, builderForValue.build());
        onChanged();
      } else {
        hitBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder addAllHit(
        java.lang.Iterable<? extends com.example.proxima.User> values) {
      if (hitBuilder_ == null) {
        ensureHitIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hit_);
        onChanged();
      } else {
        hitBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder clearHit() {
      if (hitBuilder_ == null) {
        hit_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        hitBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public Builder removeHit(int index) {
      if (hitBuilder_ == null) {
        ensureHitIsMutable();
        hit_.remove(index);
        onChanged();
      } else {
        hitBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public com.example.proxima.User.Builder getHitBuilder(
        int index) {
      return getHitFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public com.example.proxima.UserOrBuilder getHitOrBuilder(
        int index) {
      if (hitBuilder_ == null) {
        return hit_.get(index);  } else {
        return hitBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public java.util.List<? extends com.example.proxima.UserOrBuilder> 
         getHitOrBuilderList() {
      if (hitBuilder_ != null) {
        return hitBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hit_);
      }
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public com.example.proxima.User.Builder addHitBuilder() {
      return getHitFieldBuilder().addBuilder(
          com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public com.example.proxima.User.Builder addHitBuilder(
        int index) {
      return getHitFieldBuilder().addBuilder(
          index, com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <pre>
     * users who have been hit by the ping
     * </pre>
     *
     * <code>repeated .proxima.User hit = 7;</code>
     */
    public java.util.List<com.example.proxima.User.Builder> 
         getHitBuilderList() {
      return getHitFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> 
        getHitFieldBuilder() {
      if (hitBuilder_ == null) {
        hitBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder>(
                hit_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        hit_ = null;
      }
      return hitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proxima.Ping)
  }

  // @@protoc_insertion_point(class_scope:proxima.Ping)
  private static final com.example.proxima.Ping DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.proxima.Ping();
  }

  public static com.example.proxima.Ping getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ping>
      PARSER = new com.google.protobuf.AbstractParser<Ping>() {
    @java.lang.Override
    public Ping parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ping> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ping> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.proxima.Ping getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

