// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proxima.Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>.proxima.User owner = 2;</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <code>.proxima.User owner = 2;</code>
   * @return The owner.
   */
  com.example.proxima.User getOwner();
  /**
   * <code>.proxima.User owner = 2;</code>
   */
  com.example.proxima.UserOrBuilder getOwnerOrBuilder();

  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   * @return Whether the latlng field is set.
   */
  boolean hasLatlng();
  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   * @return The latlng.
   */
  com.google.type.LatLng getLatlng();
  /**
   * <code>.google.type.LatLng latlng = 3;</code>
   */
  com.google.type.LatLngOrBuilder getLatlngOrBuilder();

  /**
   * <code>repeated string tags = 4;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 4;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  java.util.List<com.example.proxima.User> 
      getOrbitList();
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  com.example.proxima.User getOrbit(int index);
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  int getOrbitCount();
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getOrbitOrBuilderList();
  /**
   * <code>repeated .proxima.User orbit = 6;</code>
   */
  com.example.proxima.UserOrBuilder getOrbitOrBuilder(
      int index);

  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  java.util.List<com.example.proxima.User> 
      getHitList();
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  com.example.proxima.User getHit(int index);
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  int getHitCount();
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getHitOrBuilderList();
  /**
   * <pre>
   * users who have been hit by the ping
   * </pre>
   *
   * <code>repeated .proxima.User hit = 7;</code>
   */
  com.example.proxima.UserOrBuilder getHitOrBuilder(
      int index);
}
