// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protos/proxima.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.proxima;

