// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

public final class ProximaProto {
  private ProximaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxima_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxima_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxima_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxima_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxima_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxima_Ping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/proxima.proto\022\007proxima\032\037google/" +
      "protobuf/timestamp.proto\032#googleapis/goo" +
      "gle/type/latlng.proto\"\037\n\013UserRequest\022\020\n\010" +
      "username\030\001 \001(\t\"\231\003\n\004User\022\013\n\003uid\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010username\030\004 " +
      "\001(\t\022\020\n\010pronouns\030\005 \001(\t\022\016\n\006secret\030\006 \001(\t\022(\n" +
      "\006status\030\007 \001(\0162\030.proxima.User.Visibility\022" +
      "\036\n\007friends\030\010 \003(\0132\r.proxima.User\022\036\n\007block" +
      "ed\030\t \003(\0132\r.proxima.User\022/\n\013create_time\030\n" +
      " \001(\0132\032.google.protobuf.Timestamp\022/\n\013upda" +
      "te_time\030\013 \001(\0132\032.google.protobuf.Timestam" +
      "p\022\034\n\005orbit\030\014 \003(\0132\r.proxima.Ping\"I\n\nVisib" +
      "ility\022\020\n\014USER_VISIBLE\020\000\022\022\n\016USER_INVISIBL" +
      "E\020\001\022\025\n\021USER_FRIENDS_ONLY\020\002\"\263\001\n\004Ping\022\013\n\003u" +
      "id\030\001 \001(\005\022\034\n\005owner\030\002 \001(\0132\r.proxima.User\022#" +
      "\n\006latlng\030\003 \001(\0132\023.google.type.LatLng\022\014\n\004t" +
      "ags\030\004 \003(\t\022\023\n\013description\030\005 \001(\t\022\034\n\005orbit\030" +
      "\006 \003(\0132\r.proxima.User\022\032\n\003hit\030\007 \003(\0132\r.prox" +
      "ima.User2;\n\007Account\0220\n\007GetUser\022\024.proxima" +
      ".UserRequest\032\r.proxima.User\"\000B%\n\023com.exa" +
      "mple.proximaB\014ProximaProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.LatLngProto.getDescriptor(),
        });
    internal_static_proxima_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proxima_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxima_UserRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_proxima_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proxima_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxima_User_descriptor,
        new java.lang.String[] { "Uid", "Name", "Email", "Username", "Pronouns", "Secret", "Status", "Friends", "Blocked", "CreateTime", "UpdateTime", "Orbit", });
    internal_static_proxima_Ping_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proxima_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxima_Ping_descriptor,
        new java.lang.String[] { "Uid", "Owner", "Latlng", "Tags", "Description", "Orbit", "Hit", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.LatLngProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
