// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

/**
 * Protobuf type {@code proxima.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proxima.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
    email_ = "";
    username_ = "";
    pronouns_ = "";
    secret_ = "";
    status_ = 0;
    friends_ = java.util.Collections.emptyList();
    blocked_ = java.util.Collections.emptyList();
    orbit_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.proxima.ProximaProto.internal_static_proxima_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.proxima.ProximaProto.internal_static_proxima_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.proxima.User.class, com.example.proxima.User.Builder.class);
  }

  /**
   * Protobuf enum {@code proxima.User.Visibility}
   */
  public enum Visibility
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_VISIBLE = 0;</code>
     */
    USER_VISIBLE(0),
    /**
     * <code>USER_INVISIBLE = 1;</code>
     */
    USER_INVISIBLE(1),
    /**
     * <code>USER_FRIENDS_ONLY = 2;</code>
     */
    USER_FRIENDS_ONLY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USER_VISIBLE = 0;</code>
     */
    public static final int USER_VISIBLE_VALUE = 0;
    /**
     * <code>USER_INVISIBLE = 1;</code>
     */
    public static final int USER_INVISIBLE_VALUE = 1;
    /**
     * <code>USER_FRIENDS_ONLY = 2;</code>
     */
    public static final int USER_FRIENDS_ONLY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Visibility valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Visibility forNumber(int value) {
      switch (value) {
        case 0: return USER_VISIBLE;
        case 1: return USER_INVISIBLE;
        case 2: return USER_FRIENDS_ONLY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Visibility>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Visibility> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Visibility>() {
            public Visibility findValueByNumber(int number) {
              return Visibility.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.proxima.User.getDescriptor().getEnumTypes().get(0);
    }

    private static final Visibility[] VALUES = values();

    public static Visibility valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Visibility(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proxima.User.Visibility)
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private int uid_ = 0;
  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public int getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRONOUNS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pronouns_ = "";
  /**
   * <code>string pronouns = 5;</code>
   * @return The pronouns.
   */
  @java.lang.Override
  public java.lang.String getPronouns() {
    java.lang.Object ref = pronouns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pronouns_ = s;
      return s;
    }
  }
  /**
   * <code>string pronouns = 5;</code>
   * @return The bytes for pronouns.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPronounsBytes() {
    java.lang.Object ref = pronouns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pronouns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object secret_ = "";
  /**
   * <pre>
   * password
   * </pre>
   *
   * <code>string secret = 6;</code>
   * @return The secret.
   */
  @java.lang.Override
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * password
   * </pre>
   *
   * <code>string secret = 6;</code>
   * @return The bytes for secret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_ = 0;
  /**
   * <code>.proxima.User.Visibility status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.proxima.User.Visibility status = 7;</code>
   * @return The status.
   */
  @java.lang.Override public com.example.proxima.User.Visibility getStatus() {
    com.example.proxima.User.Visibility result = com.example.proxima.User.Visibility.forNumber(status_);
    return result == null ? com.example.proxima.User.Visibility.UNRECOGNIZED : result;
  }

  public static final int FRIENDS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<com.example.proxima.User> friends_;
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.proxima.User> getFriendsList() {
    return friends_;
  }
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getFriendsOrBuilderList() {
    return friends_;
  }
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  @java.lang.Override
  public int getFriendsCount() {
    return friends_.size();
  }
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  @java.lang.Override
  public com.example.proxima.User getFriends(int index) {
    return friends_.get(index);
  }
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  @java.lang.Override
  public com.example.proxima.UserOrBuilder getFriendsOrBuilder(
      int index) {
    return friends_.get(index);
  }

  public static final int BLOCKED_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<com.example.proxima.User> blocked_;
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.proxima.User> getBlockedList() {
    return blocked_;
  }
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getBlockedOrBuilderList() {
    return blocked_;
  }
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  @java.lang.Override
  public int getBlockedCount() {
    return blocked_.size();
  }
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  @java.lang.Override
  public com.example.proxima.User getBlocked(int index) {
    return blocked_.get(index);
  }
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  @java.lang.Override
  public com.example.proxima.UserOrBuilder getBlockedOrBuilder(
      int index) {
    return blocked_.get(index);
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATE_TIME_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  public static final int ORBIT_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private java.util.List<com.example.proxima.Ping> orbit_;
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.proxima.Ping> getOrbitList() {
    return orbit_;
  }
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.proxima.PingOrBuilder> 
      getOrbitOrBuilderList() {
    return orbit_;
  }
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  @java.lang.Override
  public int getOrbitCount() {
    return orbit_.size();
  }
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  @java.lang.Override
  public com.example.proxima.Ping getOrbit(int index) {
    return orbit_.get(index);
  }
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  @java.lang.Override
  public com.example.proxima.PingOrBuilder getOrbitOrBuilder(
      int index) {
    return orbit_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0) {
      output.writeInt32(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pronouns_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pronouns_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secret_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, secret_);
    }
    if (status_ != com.example.proxima.User.Visibility.USER_VISIBLE.getNumber()) {
      output.writeEnum(7, status_);
    }
    for (int i = 0; i < friends_.size(); i++) {
      output.writeMessage(8, friends_.get(i));
    }
    for (int i = 0; i < blocked_.size(); i++) {
      output.writeMessage(9, blocked_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(10, getCreateTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(11, getUpdateTime());
    }
    for (int i = 0; i < orbit_.size(); i++) {
      output.writeMessage(12, orbit_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pronouns_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pronouns_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secret_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, secret_);
    }
    if (status_ != com.example.proxima.User.Visibility.USER_VISIBLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, status_);
    }
    for (int i = 0; i < friends_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, friends_.get(i));
    }
    for (int i = 0; i < blocked_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, blocked_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getCreateTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getUpdateTime());
    }
    for (int i = 0; i < orbit_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, orbit_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.proxima.User)) {
      return super.equals(obj);
    }
    com.example.proxima.User other = (com.example.proxima.User) obj;

    if (getUid()
        != other.getUid()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPronouns()
        .equals(other.getPronouns())) return false;
    if (!getSecret()
        .equals(other.getSecret())) return false;
    if (status_ != other.status_) return false;
    if (!getFriendsList()
        .equals(other.getFriendsList())) return false;
    if (!getBlockedList()
        .equals(other.getBlockedList())) return false;
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (!getOrbitList()
        .equals(other.getOrbitList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PRONOUNS_FIELD_NUMBER;
    hash = (53 * hash) + getPronouns().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getFriendsCount() > 0) {
      hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
      hash = (53 * hash) + getFriendsList().hashCode();
    }
    if (getBlockedCount() > 0) {
      hash = (37 * hash) + BLOCKED_FIELD_NUMBER;
      hash = (53 * hash) + getBlockedList().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    if (getOrbitCount() > 0) {
      hash = (37 * hash) + ORBIT_FIELD_NUMBER;
      hash = (53 * hash) + getOrbitList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.proxima.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.proxima.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.proxima.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.proxima.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.proxima.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.proxima.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.proxima.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.proxima.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.proxima.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proxima.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proxima.User)
      com.example.proxima.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proxima.ProximaProto.internal_static_proxima_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proxima.ProximaProto.internal_static_proxima_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proxima.User.class, com.example.proxima.User.Builder.class);
    }

    // Construct using com.example.proxima.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFriendsFieldBuilder();
        getBlockedFieldBuilder();
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
        getOrbitFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = 0;
      name_ = "";
      email_ = "";
      username_ = "";
      pronouns_ = "";
      secret_ = "";
      status_ = 0;
      if (friendsBuilder_ == null) {
        friends_ = java.util.Collections.emptyList();
      } else {
        friends_ = null;
        friendsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (blockedBuilder_ == null) {
        blocked_ = java.util.Collections.emptyList();
      } else {
        blocked_ = null;
        blockedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      if (orbitBuilder_ == null) {
        orbit_ = java.util.Collections.emptyList();
      } else {
        orbit_ = null;
        orbitBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.proxima.ProximaProto.internal_static_proxima_User_descriptor;
    }

    @java.lang.Override
    public com.example.proxima.User getDefaultInstanceForType() {
      return com.example.proxima.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.proxima.User build() {
      com.example.proxima.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.proxima.User buildPartial() {
      com.example.proxima.User result = new com.example.proxima.User(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.proxima.User result) {
      if (friendsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          friends_ = java.util.Collections.unmodifiableList(friends_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.friends_ = friends_;
      } else {
        result.friends_ = friendsBuilder_.build();
      }
      if (blockedBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          blocked_ = java.util.Collections.unmodifiableList(blocked_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.blocked_ = blocked_;
      } else {
        result.blocked_ = blockedBuilder_.build();
      }
      if (orbitBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0)) {
          orbit_ = java.util.Collections.unmodifiableList(orbit_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.orbit_ = orbit_;
      } else {
        result.orbit_ = orbitBuilder_.build();
      }
    }

    private void buildPartial0(com.example.proxima.User result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pronouns_ = pronouns_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.secret_ = secret_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.createTime_ = createTimeBuilder_ == null
            ? createTime_
            : createTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.updateTime_ = updateTimeBuilder_ == null
            ? updateTime_
            : updateTimeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.proxima.User) {
        return mergeFrom((com.example.proxima.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.proxima.User other) {
      if (other == com.example.proxima.User.getDefaultInstance()) return this;
      if (other.getUid() != 0) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPronouns().isEmpty()) {
        pronouns_ = other.pronouns_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (friendsBuilder_ == null) {
        if (!other.friends_.isEmpty()) {
          if (friends_.isEmpty()) {
            friends_ = other.friends_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureFriendsIsMutable();
            friends_.addAll(other.friends_);
          }
          onChanged();
        }
      } else {
        if (!other.friends_.isEmpty()) {
          if (friendsBuilder_.isEmpty()) {
            friendsBuilder_.dispose();
            friendsBuilder_ = null;
            friends_ = other.friends_;
            bitField0_ = (bitField0_ & ~0x00000080);
            friendsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFriendsFieldBuilder() : null;
          } else {
            friendsBuilder_.addAllMessages(other.friends_);
          }
        }
      }
      if (blockedBuilder_ == null) {
        if (!other.blocked_.isEmpty()) {
          if (blocked_.isEmpty()) {
            blocked_ = other.blocked_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureBlockedIsMutable();
            blocked_.addAll(other.blocked_);
          }
          onChanged();
        }
      } else {
        if (!other.blocked_.isEmpty()) {
          if (blockedBuilder_.isEmpty()) {
            blockedBuilder_.dispose();
            blockedBuilder_ = null;
            blocked_ = other.blocked_;
            bitField0_ = (bitField0_ & ~0x00000100);
            blockedBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlockedFieldBuilder() : null;
          } else {
            blockedBuilder_.addAllMessages(other.blocked_);
          }
        }
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      if (orbitBuilder_ == null) {
        if (!other.orbit_.isEmpty()) {
          if (orbit_.isEmpty()) {
            orbit_ = other.orbit_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureOrbitIsMutable();
            orbit_.addAll(other.orbit_);
          }
          onChanged();
        }
      } else {
        if (!other.orbit_.isEmpty()) {
          if (orbitBuilder_.isEmpty()) {
            orbitBuilder_.dispose();
            orbitBuilder_ = null;
            orbit_ = other.orbit_;
            bitField0_ = (bitField0_ & ~0x00000800);
            orbitBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrbitFieldBuilder() : null;
          } else {
            orbitBuilder_.addAllMessages(other.orbit_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              uid_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              pronouns_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              secret_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              com.example.proxima.User m =
                  input.readMessage(
                      com.example.proxima.User.parser(),
                      extensionRegistry);
              if (friendsBuilder_ == null) {
                ensureFriendsIsMutable();
                friends_.add(m);
              } else {
                friendsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              com.example.proxima.User m =
                  input.readMessage(
                      com.example.proxima.User.parser(),
                      extensionRegistry);
              if (blockedBuilder_ == null) {
                ensureBlockedIsMutable();
                blocked_.add(m);
              } else {
                blockedBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              com.example.proxima.Ping m =
                  input.readMessage(
                      com.example.proxima.Ping.parser(),
                      extensionRegistry);
              if (orbitBuilder_ == null) {
                ensureOrbitIsMutable();
                orbit_.add(m);
              } else {
                orbitBuilder_.addMessage(m);
              }
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int uid_ ;
    /**
     * <code>int32 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(int value) {

      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object pronouns_ = "";
    /**
     * <code>string pronouns = 5;</code>
     * @return The pronouns.
     */
    public java.lang.String getPronouns() {
      java.lang.Object ref = pronouns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pronouns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pronouns = 5;</code>
     * @return The bytes for pronouns.
     */
    public com.google.protobuf.ByteString
        getPronounsBytes() {
      java.lang.Object ref = pronouns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pronouns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pronouns = 5;</code>
     * @param value The pronouns to set.
     * @return This builder for chaining.
     */
    public Builder setPronouns(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pronouns_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string pronouns = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPronouns() {
      pronouns_ = getDefaultInstance().getPronouns();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string pronouns = 5;</code>
     * @param value The bytes for pronouns to set.
     * @return This builder for chaining.
     */
    public Builder setPronounsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pronouns_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object secret_ = "";
    /**
     * <pre>
     * password
     * </pre>
     *
     * <code>string secret = 6;</code>
     * @return The secret.
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * password
     * </pre>
     *
     * <code>string secret = 6;</code>
     * @return The bytes for secret.
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * password
     * </pre>
     *
     * <code>string secret = 6;</code>
     * @param value The secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecret(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      secret_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * password
     * </pre>
     *
     * <code>string secret = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecret() {
      secret_ = getDefaultInstance().getSecret();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * password
     * </pre>
     *
     * <code>string secret = 6;</code>
     * @param value The bytes for secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      secret_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.proxima.User.Visibility status = 7;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proxima.User.Visibility status = 7;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.proxima.User.Visibility status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.example.proxima.User.Visibility getStatus() {
      com.example.proxima.User.Visibility result = com.example.proxima.User.Visibility.forNumber(status_);
      return result == null ? com.example.proxima.User.Visibility.UNRECOGNIZED : result;
    }
    /**
     * <code>.proxima.User.Visibility status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.example.proxima.User.Visibility value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proxima.User.Visibility status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000040);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.example.proxima.User> friends_ =
      java.util.Collections.emptyList();
    private void ensureFriendsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        friends_ = new java.util.ArrayList<com.example.proxima.User>(friends_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> friendsBuilder_;

    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public java.util.List<com.example.proxima.User> getFriendsList() {
      if (friendsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(friends_);
      } else {
        return friendsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public int getFriendsCount() {
      if (friendsBuilder_ == null) {
        return friends_.size();
      } else {
        return friendsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public com.example.proxima.User getFriends(int index) {
      if (friendsBuilder_ == null) {
        return friends_.get(index);
      } else {
        return friendsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder setFriends(
        int index, com.example.proxima.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.set(index, value);
        onChanged();
      } else {
        friendsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder setFriends(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.set(index, builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder addFriends(com.example.proxima.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.add(value);
        onChanged();
      } else {
        friendsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder addFriends(
        int index, com.example.proxima.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.add(index, value);
        onChanged();
      } else {
        friendsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder addFriends(
        com.example.proxima.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.add(builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder addFriends(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.add(index, builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder addAllFriends(
        java.lang.Iterable<? extends com.example.proxima.User> values) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, friends_);
        onChanged();
      } else {
        friendsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder clearFriends() {
      if (friendsBuilder_ == null) {
        friends_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        friendsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public Builder removeFriends(int index) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.remove(index);
        onChanged();
      } else {
        friendsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public com.example.proxima.User.Builder getFriendsBuilder(
        int index) {
      return getFriendsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public com.example.proxima.UserOrBuilder getFriendsOrBuilder(
        int index) {
      if (friendsBuilder_ == null) {
        return friends_.get(index);  } else {
        return friendsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public java.util.List<? extends com.example.proxima.UserOrBuilder> 
         getFriendsOrBuilderList() {
      if (friendsBuilder_ != null) {
        return friendsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(friends_);
      }
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public com.example.proxima.User.Builder addFriendsBuilder() {
      return getFriendsFieldBuilder().addBuilder(
          com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public com.example.proxima.User.Builder addFriendsBuilder(
        int index) {
      return getFriendsFieldBuilder().addBuilder(
          index, com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User friends = 8;</code>
     */
    public java.util.List<com.example.proxima.User.Builder> 
         getFriendsBuilderList() {
      return getFriendsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> 
        getFriendsFieldBuilder() {
      if (friendsBuilder_ == null) {
        friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder>(
                friends_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        friends_ = null;
      }
      return friendsBuilder_;
    }

    private java.util.List<com.example.proxima.User> blocked_ =
      java.util.Collections.emptyList();
    private void ensureBlockedIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        blocked_ = new java.util.ArrayList<com.example.proxima.User>(blocked_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> blockedBuilder_;

    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public java.util.List<com.example.proxima.User> getBlockedList() {
      if (blockedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blocked_);
      } else {
        return blockedBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public int getBlockedCount() {
      if (blockedBuilder_ == null) {
        return blocked_.size();
      } else {
        return blockedBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public com.example.proxima.User getBlocked(int index) {
      if (blockedBuilder_ == null) {
        return blocked_.get(index);
      } else {
        return blockedBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder setBlocked(
        int index, com.example.proxima.User value) {
      if (blockedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedIsMutable();
        blocked_.set(index, value);
        onChanged();
      } else {
        blockedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder setBlocked(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (blockedBuilder_ == null) {
        ensureBlockedIsMutable();
        blocked_.set(index, builderForValue.build());
        onChanged();
      } else {
        blockedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder addBlocked(com.example.proxima.User value) {
      if (blockedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedIsMutable();
        blocked_.add(value);
        onChanged();
      } else {
        blockedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder addBlocked(
        int index, com.example.proxima.User value) {
      if (blockedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedIsMutable();
        blocked_.add(index, value);
        onChanged();
      } else {
        blockedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder addBlocked(
        com.example.proxima.User.Builder builderForValue) {
      if (blockedBuilder_ == null) {
        ensureBlockedIsMutable();
        blocked_.add(builderForValue.build());
        onChanged();
      } else {
        blockedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder addBlocked(
        int index, com.example.proxima.User.Builder builderForValue) {
      if (blockedBuilder_ == null) {
        ensureBlockedIsMutable();
        blocked_.add(index, builderForValue.build());
        onChanged();
      } else {
        blockedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder addAllBlocked(
        java.lang.Iterable<? extends com.example.proxima.User> values) {
      if (blockedBuilder_ == null) {
        ensureBlockedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocked_);
        onChanged();
      } else {
        blockedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder clearBlocked() {
      if (blockedBuilder_ == null) {
        blocked_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        blockedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public Builder removeBlocked(int index) {
      if (blockedBuilder_ == null) {
        ensureBlockedIsMutable();
        blocked_.remove(index);
        onChanged();
      } else {
        blockedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public com.example.proxima.User.Builder getBlockedBuilder(
        int index) {
      return getBlockedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public com.example.proxima.UserOrBuilder getBlockedOrBuilder(
        int index) {
      if (blockedBuilder_ == null) {
        return blocked_.get(index);  } else {
        return blockedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public java.util.List<? extends com.example.proxima.UserOrBuilder> 
         getBlockedOrBuilderList() {
      if (blockedBuilder_ != null) {
        return blockedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blocked_);
      }
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public com.example.proxima.User.Builder addBlockedBuilder() {
      return getBlockedFieldBuilder().addBuilder(
          com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public com.example.proxima.User.Builder addBlockedBuilder(
        int index) {
      return getBlockedFieldBuilder().addBuilder(
          index, com.example.proxima.User.getDefaultInstance());
    }
    /**
     * <code>repeated .proxima.User blocked = 9;</code>
     */
    public java.util.List<com.example.proxima.User.Builder> 
         getBlockedBuilderList() {
      return getBlockedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder> 
        getBlockedFieldBuilder() {
      if (blockedBuilder_ == null) {
        blockedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.proxima.User, com.example.proxima.User.Builder, com.example.proxima.UserOrBuilder>(
                blocked_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        blocked_ = null;
      }
      return blockedBuilder_;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          createTime_ != null &&
          createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreateTimeBuilder().mergeFrom(value);
        } else {
          createTime_ = value;
        }
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      if (createTime_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000200);
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          updateTime_ != null &&
          updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdateTimeBuilder().mergeFrom(value);
        } else {
          updateTime_ = value;
        }
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      if (updateTime_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public Builder clearUpdateTime() {
      bitField0_ = (bitField0_ & ~0x00000400);
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }

    private java.util.List<com.example.proxima.Ping> orbit_ =
      java.util.Collections.emptyList();
    private void ensureOrbitIsMutable() {
      if (!((bitField0_ & 0x00000800) != 0)) {
        orbit_ = new java.util.ArrayList<com.example.proxima.Ping>(orbit_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.Ping, com.example.proxima.Ping.Builder, com.example.proxima.PingOrBuilder> orbitBuilder_;

    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public java.util.List<com.example.proxima.Ping> getOrbitList() {
      if (orbitBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orbit_);
      } else {
        return orbitBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public int getOrbitCount() {
      if (orbitBuilder_ == null) {
        return orbit_.size();
      } else {
        return orbitBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public com.example.proxima.Ping getOrbit(int index) {
      if (orbitBuilder_ == null) {
        return orbit_.get(index);
      } else {
        return orbitBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder setOrbit(
        int index, com.example.proxima.Ping value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.set(index, value);
        onChanged();
      } else {
        orbitBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder setOrbit(
        int index, com.example.proxima.Ping.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.set(index, builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder addOrbit(com.example.proxima.Ping value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.add(value);
        onChanged();
      } else {
        orbitBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder addOrbit(
        int index, com.example.proxima.Ping value) {
      if (orbitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrbitIsMutable();
        orbit_.add(index, value);
        onChanged();
      } else {
        orbitBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder addOrbit(
        com.example.proxima.Ping.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.add(builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder addOrbit(
        int index, com.example.proxima.Ping.Builder builderForValue) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.add(index, builderForValue.build());
        onChanged();
      } else {
        orbitBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder addAllOrbit(
        java.lang.Iterable<? extends com.example.proxima.Ping> values) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orbit_);
        onChanged();
      } else {
        orbitBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder clearOrbit() {
      if (orbitBuilder_ == null) {
        orbit_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        orbitBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public Builder removeOrbit(int index) {
      if (orbitBuilder_ == null) {
        ensureOrbitIsMutable();
        orbit_.remove(index);
        onChanged();
      } else {
        orbitBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public com.example.proxima.Ping.Builder getOrbitBuilder(
        int index) {
      return getOrbitFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public com.example.proxima.PingOrBuilder getOrbitOrBuilder(
        int index) {
      if (orbitBuilder_ == null) {
        return orbit_.get(index);  } else {
        return orbitBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public java.util.List<? extends com.example.proxima.PingOrBuilder> 
         getOrbitOrBuilderList() {
      if (orbitBuilder_ != null) {
        return orbitBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orbit_);
      }
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public com.example.proxima.Ping.Builder addOrbitBuilder() {
      return getOrbitFieldBuilder().addBuilder(
          com.example.proxima.Ping.getDefaultInstance());
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public com.example.proxima.Ping.Builder addOrbitBuilder(
        int index) {
      return getOrbitFieldBuilder().addBuilder(
          index, com.example.proxima.Ping.getDefaultInstance());
    }
    /**
     * <pre>
     * current pings that have hit you
     * </pre>
     *
     * <code>repeated .proxima.Ping orbit = 12;</code>
     */
    public java.util.List<com.example.proxima.Ping.Builder> 
         getOrbitBuilderList() {
      return getOrbitFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.proxima.Ping, com.example.proxima.Ping.Builder, com.example.proxima.PingOrBuilder> 
        getOrbitFieldBuilder() {
      if (orbitBuilder_ == null) {
        orbitBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.proxima.Ping, com.example.proxima.Ping.Builder, com.example.proxima.PingOrBuilder>(
                orbit_,
                ((bitField0_ & 0x00000800) != 0),
                getParentForChildren(),
                isClean());
        orbit_ = null;
      }
      return orbitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proxima.User)
  }

  // @@protoc_insertion_point(class_scope:proxima.User)
  private static final com.example.proxima.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.proxima.User();
  }

  public static com.example.proxima.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.proxima.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

