// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proxima.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
