// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/proxima.proto

// Protobuf Java Version: 3.25.2
package com.example.proxima;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proxima.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string pronouns = 5;</code>
   * @return The pronouns.
   */
  java.lang.String getPronouns();
  /**
   * <code>string pronouns = 5;</code>
   * @return The bytes for pronouns.
   */
  com.google.protobuf.ByteString
      getPronounsBytes();

  /**
   * <pre>
   * password
   * </pre>
   *
   * <code>string secret = 6;</code>
   * @return The secret.
   */
  java.lang.String getSecret();
  /**
   * <pre>
   * password
   * </pre>
   *
   * <code>string secret = 6;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <code>.proxima.User.Visibility status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.proxima.User.Visibility status = 7;</code>
   * @return The status.
   */
  com.example.proxima.User.Visibility getStatus();

  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  java.util.List<com.example.proxima.User> 
      getFriendsList();
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  com.example.proxima.User getFriends(int index);
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  int getFriendsCount();
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getFriendsOrBuilderList();
  /**
   * <code>repeated .proxima.User friends = 8;</code>
   */
  com.example.proxima.UserOrBuilder getFriendsOrBuilder(
      int index);

  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  java.util.List<com.example.proxima.User> 
      getBlockedList();
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  com.example.proxima.User getBlocked(int index);
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  int getBlockedCount();
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  java.util.List<? extends com.example.proxima.UserOrBuilder> 
      getBlockedOrBuilderList();
  /**
   * <code>repeated .proxima.User blocked = 9;</code>
   */
  com.example.proxima.UserOrBuilder getBlockedOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  java.util.List<com.example.proxima.Ping> 
      getOrbitList();
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  com.example.proxima.Ping getOrbit(int index);
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  int getOrbitCount();
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  java.util.List<? extends com.example.proxima.PingOrBuilder> 
      getOrbitOrBuilderList();
  /**
   * <pre>
   * current pings that have hit you
   * </pre>
   *
   * <code>repeated .proxima.Ping orbit = 12;</code>
   */
  com.example.proxima.PingOrBuilder getOrbitOrBuilder(
      int index);
}
