// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protos/proxima.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.proxima;

@kotlin.jvm.JvmName("-initializeuserRequest")
public inline fun userRequest(block: com.example.proxima.UserRequestKt.Dsl.() -> kotlin.Unit): com.example.proxima.UserRequest =
  com.example.proxima.UserRequestKt.Dsl._create(com.example.proxima.UserRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proxima.UserRequest`
 */
public object UserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.proxima.UserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.proxima.UserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.proxima.UserRequest = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.proxima.UserRequest.copy(block: `com.example.proxima`.UserRequestKt.Dsl.() -> kotlin.Unit): com.example.proxima.UserRequest =
  `com.example.proxima`.UserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

