# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/proxima.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from googleapis.google.type import latlng_pb2 as googleapis_dot_google_dot_type_dot_latlng__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/proxima.proto\x12\x07proxima\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#googleapis/google/type/latlng.proto\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x99\x03\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08pronouns\x18\x05 \x01(\t\x12\x0e\n\x06secret\x18\x06 \x01(\t\x12(\n\x06status\x18\x07 \x01(\x0e\x32\x18.proxima.User.Visibility\x12\x1e\n\x07\x66riends\x18\x08 \x03(\x0b\x32\r.proxima.User\x12\x1e\n\x07\x62locked\x18\t \x03(\x0b\x32\r.proxima.User\x12/\n\x0b\x63reate_time\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x05orbit\x18\x0c \x03(\x0b\x32\r.proxima.Ping\"I\n\nVisibility\x12\x10\n\x0cUSER_VISIBLE\x10\x00\x12\x12\n\x0eUSER_INVISIBLE\x10\x01\x12\x15\n\x11USER_FRIENDS_ONLY\x10\x02\"\xb3\x01\n\x04Ping\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x1c\n\x05owner\x18\x02 \x01(\x0b\x32\r.proxima.User\x12#\n\x06latlng\x18\x03 \x01(\x0b\x32\x13.google.type.LatLng\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1c\n\x05orbit\x18\x06 \x03(\x0b\x32\r.proxima.User\x12\x1a\n\x03hit\x18\x07 \x03(\x0b\x32\r.proxima.User2;\n\x07\x41\x63\x63ount\x12\x30\n\x07GetUser\x12\x14.proxima.UserRequest\x1a\r.proxima.User\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.proxima_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=103
  _globals['_USERREQUEST']._serialized_end=134
  _globals['_USER']._serialized_start=137
  _globals['_USER']._serialized_end=546
  _globals['_USER_VISIBILITY']._serialized_start=473
  _globals['_USER_VISIBILITY']._serialized_end=546
  _globals['_PING']._serialized_start=549
  _globals['_PING']._serialized_end=728
  _globals['_ACCOUNT']._serialized_start=730
  _globals['_ACCOUNT']._serialized_end=789
# @@protoc_insertion_point(module_scope)
